apiVersion: skaffold/v2beta16
kind: Config
metadata:
  name: spring-boot-poc
build:
  artifacts:
  - image: spring-boot-poc
    context: .
    jib: {}
  local: {}

deploy:
  kubectl:
    manifests:
    - k8s/deploy.yaml
